### PR TITLE
DEV - ChatGPT integration

### PR DESCRIPTION
**Pull request by mertyldrr**

### CODE REVIEW

**Comment by NCEghtebas** [comment]
Would also solve [#86](https://github.com/TUMFARSynchrony/experimental-hub/issues/86)

**Comment by BorderBoy** [comment]
I tried reviewing the DEV - ChatGPT PR and got the following error in the frontend when trying to send a chat message: "Message data is not a valid ChatMessage."
In the backend it gives the following error: "2024-03-04 20:08:01,709:DEBUG:TypesUtil: Missing key: sentiment_score" 
Seems like the error is in chat_message.py:is_valid_chatmessage()

**Comment by BorderBoy** [comment]
Hey, I tested everything and it seems to work good now 👍. ChatGPT, chat notifications/changes and sentiment analysis all work.
Just a question about the sentiment analysis labels. So I guess red/green, means positive/negative. But what exactly does the score represent?

**Review by BorderBoy — APPROVED** [review]

**Comment by BorderBoy** [comment]
Actually now I have an issue, that messages are not always delivered from participant to experimenter.

Also maybe another thing for the future. Currently, chat filters are not shown in the overview screen, where the invite link can be copied.

**Comment by mertyldrr** [comment]
@BorderBoy For the experimenter, each message will be rendered if you select that user from the dropdown, we thought it would be very messy to display them on the same tab if you have many participants and getting lots of messages. If you already knew this and still not working, do you see any error somewhere(in the console or an error snackbar)?

**Comment by BorderBoy** [comment]
There are no errors, but I can now reproduce it. If I join as a participant and write something to the experimenter, without changing the dropdown. It says "Me to undefined (Privately)" and will not be delivered to the experimenter (actually its send to another participant). If I switch to another participant and then back to the experimenter, then it's actually send to the experimenter.

**Comment by mertyldrr** [comment]
@BorderBoy Hm, the default state must be wrong initially, thanks for testing this 👍

**Comment by mertyldrr** [comment]
@BorderBoy could you re-test the issue you mentioned? should be fixed now

I forgot to explain the scores, sorry about that.

We are using roBERTa-base pre-trained model for sentiment analysis and the result for a sentence looks like this:

```
1) positive 0.8466
2) neutral 0.1458
3) negative 0.0076
```

which means a sentence is evaluated as positive by a large margin.

another example:
```
1) positive 0.5
2) neutral 0.4
3) negative 0.1
```
a result like this again says that the sentence is evaluated as positive but it's also close to neutral.

**Review by BorderBoy — APPROVED** [review]
Thanks for the explanation. The bug is also fixed now!

**Review by BorderBoy — APPROVED** [review]
I just tested everything again. I noticed that the frontend crashes when no API is defined and you click on the ChatGPT tab. I uncommented the API key line in the .env file. This means it's not crashing when nothing is changed in the file, but ChatGPT will not work, because there is no valid key in there. We still need an error message when the key is invalid, but I created an issue (#225) for that.
I think this branch is ready to merge.

**Review by NCEghtebas — APPROVED** [review]

**Comment by NCEghtebas** [comment]
Closed issue #86

**Pull request merged**
