### PR TITLE
Asymmetric Canvas

### PR DESCRIPTION
**Pull request by mrahtapot**
This PR adds the asymmetry functionality to the codebase. With asymmetry, experimenters can set up different canvas views for different participants and when the experiment starts, the participant should see the other participants in a different view than the default one the experimenter sees.

The cases of
- creating a new participant
- deleting a participant
- cancelling asymmetry changes
are all accounted for.

Future work:
- asymmetric filters
- hiding a participant in an asymmetric view (mute video is also a filter, hence this is an extension of filters)

### CODE REVIEW

**Review by BorderBoy — APPROVED** [review]
I tested it and everything works as expected.
Just a small suggestion: If an experimenter has to set up many asymmetrical views, it might be nice if the colors of the participants would stay consistent. Maybe we can seed the random color with the paricipant name or id?

**Review by mertyldrr — APPROVED** [review]
asymmetric view is working as described

**Comment by NCEghtebas** [comment]
before merging to main, I would like to try 1) evaluating the feature with a user. 2) trying it out with other participants joning the session. I think this is the start of a great completely new feature!

**Comment by BorderBoy** [comment]
I just pulled the changes and tried to run `npm run build` and got the following error: 
```Module not found: Error: Can't resolve '../../filters_data.json' in '/Users/jonasgoos/Desktop/gits/experimental-hub/frontend/src/modals/ParticipantDataModal'```

Does this also happen for you?

**Comment by gulbikeimge** [comment]
> I just pulled the changes and tried to run `npm run build` and got the following error: `Module not found: Error: Can't resolve '../../filters_data.json' in '/Users/jonasgoos/Desktop/gits/experimental-hub/frontend/src/modals/ParticipantDataModal'`
> 
> Does this also happen for you?

I also got this error, fixed the issues now

**Review by BorderBoy — APPROVED** [review]
Yeah that fixed the error.

**Pull request merged**
