### PR TITLE
fix: place post-processing button back

### PR DESCRIPTION
**Pull request by mrahtapot**
Post-processing button is placed back to session overview header
@normaps

### CODE REVIEW

**Review by normaps — APPROVED** [review]
Tested & LGTM :)

**Comment by NCEghtebas** [comment]
I could see a usability issue with how to nagivate back to the Session Overview Page, could we resolve that in this PR as well by using our new template for the session overview @normaps @mrahtapot @bikemc?

**Comment by mrahtapot** [comment]
> I could see a usability issue with how to nagivate back to the Session Overview Page, could we resolve that in this PR as well by using our new template for the session overview @normaps @mrahtapot @bikemc?

you mean post-processing room right? Just done, could you check? If everything's alright, I can rebase and merge :)

**Comment by normaps** [comment]
Oh right, I already checked the latest commit, the navigation to go back to the session overview is there now 👍  @mrahtapot @NCEghtebas

**Comment by NCEghtebas** [comment]
thank you @mrahtapot and @normaps

**Pull request merged**
