### PR TITLE
Fix for duplicating a session

### PR DESCRIPTION
**Pull request by tobifb**
set end and start time to 0 when duplicating a session

Test:
- start and end an experiment
- duplicate the experiment

### CODE REVIEW

**Comment by VanessaVanessaC** [comment]
Thanks for the quick fix. I have no errors anymore!

**Comment by tobifb** [comment]
Added resetting notes, log and chat for every participant. (Fixes issue #177

**Review by VanessaVanessaC — CHANGES_REQUESTED** [review]
when duplicating the chat was cleared, but there was still a red dot.

**Review by mertyldrr — APPROVED** [review]
@VanessaVanessaC notification bug will be fixed in #169

I think we can merge this PR, looks good

**Pull request merged**
